import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const contractsRoot = fileURLToPath(new URL('../packages/contracts/', import.meta.url));

const contracts = [
  { name: 'PayeeLock', source: 'PayeeLock.sol', output: 'payeelock.abi.ts' },
  { name: 'PayeeLockFactory', source: 'PayeeLockFactory.sol', output: 'payee-lock-factory.abi.ts' },
  {
    name: 'WorkspaceResolver',
    source: 'WorkspaceResolver.sol',
    output: 'workspace-resolver.abi.ts',
  },
  { name: 'TestUSD', source: 'TestFixtures.sol', output: 'test-usd.abi.ts' },
  { name: 'TestResolver', source: 'TestFixtures.sol', output: 'test-resolver.abi.ts' },
] as const;

for (const { name, source, output } of contracts) {
  const artifact = JSON.parse(
    await readFile(path.join(contractsRoot, 'out', source, `${name}.json`), 'utf8'),
  );
  await writeFile(
    path.join(contractsRoot, 'generated', output),
    `// Generated by npm run contracts:build.\nexport const ${name[0].toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
  );
}

// Deployable bytecode lets the web app create a buyer-owned workspace with no
// pre-deployed infrastructure and no server-side signing key.
const deployables = [
  { name: 'PayeeLock', source: 'PayeeLock.sol', output: 'payeelock.bytecode.ts' },
  {
    name: 'WorkspaceResolver',
    source: 'WorkspaceResolver.sol',
    output: 'workspace-resolver.bytecode.ts',
  },
  { name: 'TestUSD', source: 'TestFixtures.sol', output: 'test-usd.bytecode.ts' },
] as const;

for (const { name, source, output } of deployables) {
  const artifact = JSON.parse(
    await readFile(path.join(contractsRoot, 'out', source, `${name}.json`), 'utf8'),
  );
  await writeFile(
    path.join(contractsRoot, 'generated', output),
    `// Generated by npm run contracts:build.\nexport const ${name[0].toLowerCase() + name.slice(1)}Bytecode = '${artifact.bytecode.object}' as const;\n`,
  );
}
