import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const contractsRoot = fileURLToPath(new URL('../packages/contracts/', import.meta.url));

const contracts = [
  { name: 'PayeeLock', source: 'PayeeLock.sol', output: 'payeelock.abi.ts' },
  { name: 'TestUSD', source: 'TestFixtures.sol', output: 'test-usd.abi.ts' },
  { name: 'TestResolver', source: 'TestFixtures.sol', output: 'test-resolver.abi.ts' },
] as const;

for (const { name, source, output } of contracts) {
  const artifact = JSON.parse(
    await readFile(path.join(contractsRoot, 'out', source, `${name}.json`), 'utf8'),
  );
  await writeFile(
    path.join(contractsRoot, 'generated', output),
    `// Generated by npm run contracts:build.\nexport const ${name[0].toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
  );
}
